<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderT extends \App\Entity\OrderT implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'id', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'user', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'startDepartment', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'endDepartment', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'reserved_at', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'finished_at', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'price', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'equipments'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'id', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'user', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'startDepartment', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'endDepartment', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'reserved_at', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'finished_at', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'price', '' . "\0" . 'App\\Entity\\OrderT' . "\0" . 'equipments'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrderT $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\Symfony\Component\Security\Core\User\UserInterface $user): \App\Entity\OrderT
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDepartment(): ?\App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDepartment', []);

        return parent::getStartDepartment();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDepartment(?\App\Entity\Department $startDepartment): \App\Entity\OrderT
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDepartment', [$startDepartment]);

        return parent::setStartDepartment($startDepartment);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDepartment(): ?\App\Entity\Department
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDepartment', []);

        return parent::getEndDepartment();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDepartment(?\App\Entity\Department $endDepartment): \App\Entity\OrderT
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDepartment', [$endDepartment]);

        return parent::setEndDepartment($endDepartment);
    }

    /**
     * {@inheritDoc}
     */
    public function getcreated_at(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcreated_at', []);

        return parent::getcreated_at();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $created_at): \App\Entity\OrderT
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getreserved_at(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getreserved_at', []);

        return parent::getreserved_at();
    }

    /**
     * {@inheritDoc}
     */
    public function setReservedAt(?\DateTimeInterface $reserved_at): \App\Entity\OrderT
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReservedAt', [$reserved_at]);

        return parent::setReservedAt($reserved_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getfinished_at(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getfinished_at', []);

        return parent::getfinished_at();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinishedAt(?\DateTimeInterface $finished_at): \App\Entity\OrderT
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinishedAt', [$finished_at]);

        return parent::setFinishedAt($finished_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(?float $price): \App\Entity\OrderT
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipments', []);

        return parent::getEquipments();
    }

    /**
     * {@inheritDoc}
     */
    public function addEquipment(\App\Entity\Equipment $equipment): \App\Entity\OrderT
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEquipment', [$equipment]);

        return parent::addEquipment($equipment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEquipment(\App\Entity\Equipment $equipment): \App\Entity\OrderT
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEquipment', [$equipment]);

        return parent::removeEquipment($equipment);
    }

}
